# Exported from Render on 2024-11-30T10:50:23Z
services:
- type: web
  name: Photobooth
  runtime: python
  repo: https://github.com/ItsHarshitAg/Photobooth
  plan: free
  envVars:
  - key: PORT
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
version: "1"